name: ci

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  docker-libs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: [ {suffix: '', file: 'docker/libs/Dockerfile'},  {suffix: 'musl', file: 'docker/libs/Dockerfile.musl'} ] 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set build args
        id: args
        shell: bash
        run: |
          echo "FALCO_LIBS_VERSION=$(awk -F'=' '/FALCO_LIBS_VERSION/{print $2}' manifest)" >> $GITHUB_ENV
          echo "FALCO_LIBS_VERSION_SHORT=$(V=$(awk -F'=' '/FALCO_LIBS_VERSION/{print $2}' manifest); echo ${V:0:7})" >> $GITHUB_ENV
          echo "FALCO_LIBS_DRIVER_VERSION=$(awk -F'=' '/FALCO_LIBS_DRIVER_VERSION/{print $2}' manifest)" >> $GITHUB_ENV
          echo "FALCO_VERSION=$(awk -F'=' '/FALCO_VERSION/{print $2}' manifest)" >> $GITHUB_ENV
          echo "FALCO_FIELDS_CHECKSUM=$(awk -F'=' '/FALCO_FIELDS_CHECKSUM/{print $2}' manifest)" >> $GITHUB_ENV
      - name: Check if image exists
        id: checks
        shell: bash
        run: |
          echo "SUFFIX=$([ ! -z '${{ matrix.image.suffix }}' ] && echo '-${{ matrix.image.suffix }}' || echo '')" >> $GITHUB_ENV
          echo "##[set-output name=libs_exists;] $(curl --silent -f --head -lL https://docker.pkg.github.com/v2/${{ github.repository }}/libs${{ env.SUFFIX }}/manifests/${{ env.FALCO_LIBS_VERSION }} -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} > /dev/null && echo 1 || echo 0)"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.checks.outputs.libs_exists == 0 || github.event_name == 'workflow_dispatch' }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        if: ${{ steps.checks.outputs.libs_exists == 0 || github.event_name == 'workflow_dispatch' }}
        with:
          images: |
            ghcr.io/${{ github.repository }}/libs${{ env.SUFFIX }}
          tags: |
            type=raw,value=${{ env.FALCO_LIBS_VERSION }}
            type=raw,value=${{ env.FALCO_LIBS_VERSION_SHORT }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ steps.checks.outputs.libs_exists == 0 || github.event_name == 'workflow_dispatch' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ steps.checks.outputs.libs_exists == 0 || github.event_name == 'workflow_dispatch' }}
        with:
          tags: "${{ steps.meta.outputs.tags }}"
          push: true
          file: ${{ matrix.image.file }}
          build-args: |
            FALCO_LIBS_VERSION=${{ env.FALCO_LIBS_VERSION }}
            FALCO_LIBS_DRIVER_VERSION=${{ env.FALCO_LIBS_DRIVER_VERSION }}
            FALCO_VERSION=${{ env.FALCO_VERSION }}
            FALCO_FIELDS_CHECKSUM=${{ env.FALCO_FIELDS_CHECKSUM }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        if: ${{ steps.checks.outputs.libs_exists == 0 || github.event_name == 'workflow_dispatch' }}
  docker-runtime:
    needs: docker-libs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: [ {suffix: '', file: 'docker/driver-loader/Dockerfile'},  {suffix: 'ubi', file: 'docker/driver-loader/Dockerfile.ubi'} ] 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set build args
        id: args
        shell: bash
        run: |
          echo "UBI_VERSION=$(awk -F'=' '/UBI_VERSION/{print $2}' manifest)" >> $GITHUB_ENV
          echo "FALCO_LIBS_VERSION=$(awk -F'=' '/FALCO_LIBS_VERSION/{print $2}' manifest)" >> $GITHUB_ENV
          echo "FALCO_LIBS_DRIVER_VERSION=$(awk -F'=' '/FALCO_LIBS_DRIVER_VERSION/{print $2}' manifest)" >> $GITHUB_ENV
          echo "FALCO_LIBS_DRIVER_VERSION_SHORT=$(V=$(awk -F'=' '/FALCO_LIBS_DRIVER_VERSION/{print $2}' manifest); echo ${V:0:7})" >> $GITHUB_ENV
      - name: Check if image exists
        id: checks
        shell: bash
        run: |
          echo "SUFFIX=$([ ! -z '${{ matrix.image.suffix }}' ] && echo '-${{ matrix.image.suffix }}' || echo '')" >> $GITHUB_ENV
          echo "##[set-output name=runtime_exists;] $(curl --silent -f --head -lL https://docker.pkg.github.com/v2/${{ github.repository }}/runtime${{ env.SUFFIX }}/manifests/${{ env.FALCO_LIBS_DRIVER_VERSION }} -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} > /dev/null && echo 1 || echo 0)"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.checks.outputs.runtime_exists == 0 || github.event_name == 'workflow_dispatch' }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        if: ${{ steps.checks.outputs.runtime_exists == 0 || github.event_name == 'workflow_dispatch' }}
        with:
          images: |
            ghcr.io/${{ github.repository }}/runtime${{ env.SUFFIX }}
          tags: |
            type=raw,value=${{ env.FALCO_LIBS_DRIVER_VERSION }},enable=${{ matrix.image.suffix == '' }}
            type=raw,value=${{ env.FALCO_LIBS_DRIVER_VERSION_SHORT }},enable=${{ matrix.image.suffix == '' }}
            type=raw,value=${{ env.UBI_VERSION }}-${{ env.FALCO_LIBS_DRIVER_VERSION }},enable=${{ matrix.image.suffix == 'ubi' }}
            type=raw,value=${{ env.UBI_VERSION }}-${{ env.FALCO_LIBS_DRIVER_VERSION_SHORT }},enable=${{ matrix.image.suffix == 'ubi' }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ steps.checks.outputs.runtime_exists == 0 || github.event_name == 'workflow_dispatch' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ steps.checks.outputs.runtime_exists == 0 || github.event_name == 'workflow_dispatch' }}
        with:
          tags: "${{ steps.meta.outputs.tags }}"
          push: true
          file: ${{ matrix.image.file }}
          build-args: |
            FALCO_LIBS_VERSION=${{ env.FALCO_LIBS_VERSION }}
            FALCO_LIBS_DRIVER_VERSION=${{ env.FALCO_LIBS_DRIVER_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        if: ${{ steps.checks.outputs.runtime_exists == 0 || github.event_name == 'workflow_dispatch' }}

