name: ci

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  docker-libs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}/libs
          tags: |
            type=sha,prefix=
            type=sha,format=long,prefix=
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set build args
        id: args
        shell: bash
        run: |
          echo "FALCOSECURITY_LIBS_VERSION=${{ github.sha }}" >> $GITHUB_ENV
          echo "FALCOSECURITY_LIBS_DRIVER_VERSION=${{ github.sha }}" >> $GITHUB_ENV
          echo "FALCOSECURITY_LIBS_CHECKSUM=$(wget -qO- https://github.com/falcosecurity/libs/archive/${{ github.sha }}.tar.gz | sha256sum | cut -d " " -f 1)" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: "${{ steps.meta.outputs.tags }}"
          push: true
          file: "docker/libs/Dockerfile"
          build-args: |
            FALCOSECURITY_LIBS_VERSION=${{ env.FALCOSECURITY_LIBS_VERSION }}
            FALCOSECURITY_LIBS_DRIVER_VERSION=${{ env.FALCOSECURITY_LIBS_DRIVER_VERSION }}
            FALCOSECURITY_LIBS_CHECKSUM=${{ env.FALCOSECURITY_LIBS_CHECKSUM }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  docker-runtime:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}/runtime
          tags: |
            type=sha,prefix=
            type=sha,format=long,prefix=
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set build args
        id: args
        shell: bash
        run: |
          echo "FALCOSECURITY_LIBS_VERSION=${{ github.sha }}" >> $GITHUB_ENV
          echo "FALCOSECURITY_LIBS_DRIVER_VERSION=${{ github.sha }}" >> $GITHUB_ENV
          echo "FALCOSECURITY_LIBS_CHECKSUM=$(wget -qO- https://github.com/falcosecurity/libs/archive/${{ github.sha }}.tar.gz | sha256sum | cut -d " " -f 1)" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: "${{ steps.meta.outputs.tags }}"
          push: true
          file: "docker/driver-loader/Dockerfile"
          build-args: |
            FALCOSECURITY_LIBS_VERSION=${{ env.FALCOSECURITY_LIBS_VERSION }}
            FALCOSECURITY_LIBS_DRIVER_VERSION=${{ env.FALCOSECURITY_LIBS_DRIVER_VERSION }}
            FALCOSECURITY_LIBS_CHECKSUM=${{ env.FALCOSECURITY_LIBS_CHECKSUM }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}